# 1. Isabel's Method

In [11]:
from ropt_aqc.initialise_hamiltonians import get_hamiltonian_terms, build_matrix_from_terms

num_sites = 6
degree = 2
n_repetitions = 5
n_id_layers = 0
J=1.

In [12]:
# Ising-1d
t = 2.0
g=0.75
h=0.6
system = 'ising-1d'

terms, params = get_hamiltonian_terms(num_qubits=num_sites, system=system, J=J, g=g, h=h)
H = build_matrix_from_terms(terms, num_qubits=num_sites)
print('H: ', H)

J = params['J']
h = params['h']
g = params['g']
print('J: ', J, '\nh : ', h, '\ng: ', g)

H:  [[ 8.60000014+0.j  0.75      +0.j  0.75      +0.j ...  0.        +0.j
   0.        +0.j  0.        +0.j]
 [ 0.75      +0.j  5.4000001 +0.j  0.        +0.j ...  0.        +0.j
   0.        +0.j  0.        +0.j]
 [ 0.75      +0.j  0.        +0.j  3.4000001 +0.j ...  0.        +0.j
   0.        +0.j  0.        +0.j]
 ...
 [ 0.        +0.j  0.        +0.j  0.        +0.j ... -1.4000001 +0.j
   0.        +0.j  0.75      +0.j]
 [ 0.        +0.j  0.        +0.j  0.        +0.j ...  0.        +0.j
   0.5999999 +0.j  0.75      +0.j]
 [ 0.        +0.j  0.        +0.j  0.        +0.j ...  0.75      +0.j
   0.75      +0.j  1.39999986+0.j]]
J:  [[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]] 
h :  [0.6 0.6 0.6 0.6 0.6 0.6] 
g:  [0.75 0.75 0.75 0.75 0.75 0.75]


In [4]:
from ropt_aqc.spin_systems import get_brickwall_trotter_gates_spin_chain

gates_ising = get_brickwall_trotter_gates_spin_chain(t=t, n_sites=num_sites, n_repetitions=n_repetitions, hamiltonian=system, degree=degree, J=J, g=g, h=h)
print(gates_ising)

[[[-0.46315726-0.74838398j -0.13740889-0.14277023j
   -0.11989611-0.35986465j -0.19335713+0.06983982j]
  [-0.13740889-0.14277023j  0.48569208+0.54275229j
   -0.191431  -0.08079152j  0.19101622-0.59211343j]
  [-0.11989611-0.35986465j -0.191431  -0.08079152j
    0.04743641+0.86235423j  0.17119208-0.19426141j]
  [-0.19335713+0.06983982j  0.19101622-0.59211343j
    0.17119208-0.19426141j  0.69040577-0.164151j  ]]

 [[-0.10852358-0.92225425j -0.07795195-0.23668229j
   -0.07795195-0.23668229j -0.10937167+0.03895572j]
  [-0.07795195-0.23668229j  0.43143695+0.79958483j
   -0.10886535-0.04188616j  0.09704272-0.29901144j]
  [-0.07795195-0.23668229j -0.10886535-0.04188616j
    0.43143695+0.79958483j  0.09704272-0.29901144j]
  [-0.10937167+0.03895572j  0.09704272-0.29901144j
    0.09704272-0.29901144j  0.7942361 -0.39756641j]]

 [[-0.46315726-0.74838398j -0.11989611-0.35986465j
   -0.13740889-0.14277023j -0.19335713+0.06983982j]
  [-0.11989611-0.35986465j  0.04743641+0.86235423j
   -0.191431  -0.0

In [4]:
from ropt_aqc.initialise_hamiltonians import get_hamiltonian_terms

ising_terms = get_hamiltonian_terms(6, 'ising-1d', J=1.0, h=0.6, g=0.75)

In [5]:
from ropt_aqc.initialise_hamiltonians import build_matrix_from_terms

H_ising = build_matrix_from_terms(ising_terms, 6)

from jax import numpy as jnp
H_real = jnp.real(H_ising)
with jnp.printoptions(precision=2, suppress=True):
    print(H_real)

[[ 8.6   0.75  0.75 ...  0.    0.    0.  ]
 [ 0.75  5.4   0.   ...  0.    0.    0.  ]
 [ 0.75  0.    3.4  ...  0.    0.    0.  ]
 ...
 [ 0.    0.    0.   ... -1.4   0.    0.75]
 [ 0.    0.    0.   ...  0.    0.6   0.75]
 [ 0.    0.    0.   ...  0.75  0.75  1.4 ]]


In [6]:
from ropt_aqc.circuit_building import build_trotterised_brickwall_circuit

qc_ising_sp = build_trotterised_brickwall_circuit(hamiltonian_terms=ising_terms, system='ising-1d', num_qubits=6, time=1, num_steps=10)
# qc_ising_sp.draw("mpl")

Step 0: Applying gates for pairs:
Even pair: (0, 1)
Odd pair: (1, 2)
Even pair: (2, 3)
Odd pair: (3, 4)
Even pair: (4, 5)
Step 1: Applying gates for pairs:
Even pair: (0, 1)
Odd pair: (1, 2)
Even pair: (2, 3)
Odd pair: (3, 4)
Even pair: (4, 5)
Step 2: Applying gates for pairs:
Even pair: (0, 1)
Odd pair: (1, 2)
Even pair: (2, 3)
Odd pair: (3, 4)
Even pair: (4, 5)
Step 3: Applying gates for pairs:
Even pair: (0, 1)
Odd pair: (1, 2)
Even pair: (2, 3)
Odd pair: (3, 4)
Even pair: (4, 5)
Step 4: Applying gates for pairs:
Even pair: (0, 1)
Odd pair: (1, 2)
Even pair: (2, 3)
Odd pair: (3, 4)
Even pair: (4, 5)
Step 5: Applying gates for pairs:
Even pair: (0, 1)
Odd pair: (1, 2)
Even pair: (2, 3)
Odd pair: (3, 4)
Even pair: (4, 5)
Step 6: Applying gates for pairs:
Even pair: (0, 1)
Odd pair: (1, 2)
Even pair: (2, 3)
Odd pair: (3, 4)
Even pair: (4, 5)
Step 7: Applying gates for pairs:
Even pair: (0, 1)
Odd pair: (1, 2)
Even pair: (2, 3)
Odd pair: (3, 4)
Even pair: (4, 5)
Step 8: Applying gates f

In [16]:
# qc_ising_sp.draw("mpl")

In [7]:
from ropt_aqc.circuit_building import extract_gate_matrices
gate_seq_ising = extract_gate_matrices(qc_ising_sp)
print(gate_seq_ising)

[(array([[0.99718882+0.j        , 0.        -0.07492971j],
       [0.        -0.07492971j, 0.99718882+0.j        ]]), [0]), (array([[0.99820054-0.05996401j, 0.        +0.j        ],
       [0.        +0.j        , 0.99820054+0.05996401j]]), [0]), (array([[0.99718882+0.j        , 0.        -0.07492971j],
       [0.        -0.07492971j, 0.99718882+0.j        ]]), [1]), (array([[0.99820054-0.05996401j, 0.        +0.j        ],
       [0.        +0.j        , 0.99820054+0.05996401j]]), [1]), (array([[0.99718882+0.j        , 0.        -0.07492971j],
       [0.        -0.07492971j, 0.99718882+0.j        ]]), [2]), (array([[0.99820054-0.05996401j, 0.        +0.j        ],
       [0.        +0.j        , 0.99820054+0.05996401j]]), [2]), (array([[0.99718882+0.j        , 0.        -0.07492971j],
       [0.        -0.07492971j, 0.99718882+0.j        ]]), [3]), (array([[0.99820054-0.05996401j, 0.        +0.j        ],
       [0.        +0.j        , 0.99820054+0.05996401j]]), [3]), (array([[0.9971

In [8]:
gate_seq_2q = [(U, q) for (U, q) in gate_seq_ising if len(q) == 2]

In [9]:
import numpy as np
from functools import reduce
def embed_two_qubit_gate(U, i, j, num_qubits):
    """
    Embed a 4x4 two-qubit gate U acting on qubits (i, j) into a 2^n x 2^n system.
    """
    import numpy as np
    from functools import reduce

    assert i < j, "Qubit i must be less than j"

    I = np.eye(2)
    
    # Identity operators before, between, after
    before = [I] * i
    middle = [I] * (j - i - 1)
    after = [I] * (num_qubits - j - 1)

    # Build full operator: I^{⊗i} ⊗ U ⊗ I^{⊗n-j-1}
    ops = before + [U] + middle + after

    return reduce(np.kron, ops)


In [10]:
num_qubits = 6

# Method 1: From Qiskit
U_qiskit = np.eye(2**num_qubits, dtype=complex)
for U, (i, j) in gate_seq_2q:
    U_qiskit = embed_two_qubit_gate(U, min(i,j), max(i,j), num_qubits) @ U_qiskit


# Method 2: From matrix list (assume brickwall pattern)
def get_brickwall_pairs(n_qubits, n_layers):
    pairs = []
    for layer in range(n_layers):
        offset = layer % 2
        layer_pairs = [(i, i + 1) for i in range(offset, n_qubits - 1, 2)]
        pairs.extend(layer_pairs)
    return pairs

pairs = get_brickwall_pairs(num_qubits, len(gates_ising))
U_precompiled = np.eye(2**num_qubits, dtype=complex)
for U, (i, j) in zip(gates_ising, pairs):
    U_precompiled = embed_two_qubit_gate(U, i, j, num_qubits) @ U_precompiled


In [11]:
from qiskit.quantum_info import Statevector

psi0 = Statevector.from_label('0' * num_qubits).data
psi_qiskit = U_qiskit @ psi0
psi_precompiled = U_precompiled @ psi0

fidelity = np.abs(np.vdot(psi_qiskit, psi_precompiled))**2
print(f'Fidelity between Qiskit and Precompiled evolution: {fidelity:.8f}')


Fidelity between Qiskit and Precompiled evolution: 0.80177115


In [12]:
gate_seq_2q = [(U, q) for (U, q) in extract_gate_matrices(qc_ising_sp) if len(q) == 2]
print("Qiskit 2-qubit gate count:", len(gate_seq_2q))


Qiskit 2-qubit gate count: 50


In [13]:
def get_2q_per_layer(n_qubits):
    return n_qubits // 2 if n_qubits % 2 == 0 else n_qubits // 2  # Same for even/odd

n_qubits = 6
per_layer = get_2q_per_layer(n_qubits)
num_layers_qiskit = len(gate_seq_2q) // per_layer
print("Inferred Qiskit Trotter layers:", num_layers_qiskit)


Inferred Qiskit Trotter layers: 16


In [14]:
print("Precompiled gate count:", len(gates_ising))


Precompiled gate count: 2560


In [15]:
import numpy as np
from qiskit import QuantumCircuit
from qiskit.circuit.library import RZZGate

# Define a helper function to print the pair sequence for Qiskit and JAX circuits
def print_pair_sequence_qiskit(circuit):
    pairs = []
    for gate, qargs, _ in circuit.data:
        if isinstance(gate, RZZGate):  # We're looking for RZZ gates
            pairs.append(tuple(qargs))
    print(f"Pair sequence (Qiskit): {pairs}")
    return pairs

def print_pair_sequence_jax(gates_ising, num_qubits, system='ising-1d'):
    # Extracting the pairs from the precompiled JAX gates, assume gates_ising is a JAX array
    pairs = []
    for i in range(0, num_qubits-1, 2):
        pairs.append((i, i+1))
    # For odd pairs (in a brickwall pattern)
    for i in range(1, num_qubits-1, 2):
        pairs.append((i, i+1))
    print(f"Pair sequence (JAX): {pairs}")
    return pairs

# Function to print the angles for RZZ gates in both circuits
def print_rzz_gate_angles(circuit):
    angles = []
    for gate, qargs, _ in circuit.data:
        if isinstance(gate, RZZGate):
            # Remove .evalf() as the parameter is already a float
            angle = gate.params[0]
            angles.append((tuple(qargs), angle))
    print(f"RZZ gate angles (Qiskit): {angles}")
    return angles


def print_rzz_gate_angles_jax(gates_ising, num_qubits):
    angles = []
    # Assuming gates_ising is a JAX array or similar that stores gate info
    # You'll have to extract the angles from the gates
    for i in range(0, num_qubits-1, 2):  # Even layer RZZ gates
        angle = 2 * 1.0  # Replace with actual angle computation from JAX
        angles.append(((i, i+1), angle))
    for i in range(1, num_qubits-1, 2):  # Odd layer RZZ gates
        angle = 2 * 1.0  # Replace with actual angle computation from JAX
        angles.append(((i, i+1), angle))
    print(f"RZZ gate angles (JAX): {angles}")
    return angles

# Main comparison function
def compare_circuits(circuit_qiskit, gates_ising, num_qubits, system='ising-1d'):
    # Step 1: Compare the pair sequence
    print("Checking pair sequence...")
    pairs_qiskit = print_pair_sequence_qiskit(circuit_qiskit)
    pairs_jax = print_pair_sequence_jax(gates_ising, num_qubits)
    print(f"Pair sequence match: {pairs_qiskit == pairs_jax}")

    # Step 2: Compare the RZZ gate angles
    print("Checking RZZ gate angles...")
    angles_qiskit = print_rzz_gate_angles(circuit_qiskit)
    angles_jax = print_rzz_gate_angles_jax(gates_ising, num_qubits)
    print(f"RZZ angles match: {angles_qiskit == angles_jax}")

    # Step 3: Compare the unitary matrices for one Trotter step (this can be done later)
    print("Unitary comparison can be added here...")

# Example usage
from ropt_aqc.circuit_building import build_trotterised_brickwall_circuit
from ropt_aqc.initialise_hamiltonians import get_hamiltonian_terms

# Define the system and parameters
num_qubits = 6
time = 1.0
num_steps = 10
ising_terms = get_hamiltonian_terms(num_qubits, 'ising-1d', J=1.0, h=0.6, g=0.75)

# Build the Qiskit circuit
qc_ising_sp = build_trotterised_brickwall_circuit(hamiltonian_terms=ising_terms, system='ising-1d', num_qubits=num_qubits, time=time, num_steps=num_steps)

# For the precompiled version, use your precompiled gate construction logic (replace `gates_ising` with actual precompiled circuit)
# gates_ising = ... (Your precompiled circuit here)

# Compare the circuits
compare_circuits(qc_ising_sp, gates_ising, num_qubits)


Step 0: Applying gates for pairs:
Even pair: (0, 1)
Odd pair: (1, 2)
Even pair: (2, 3)
Odd pair: (3, 4)
Even pair: (4, 5)
Step 1: Applying gates for pairs:
Even pair: (0, 1)
Odd pair: (1, 2)
Even pair: (2, 3)
Odd pair: (3, 4)
Even pair: (4, 5)
Step 2: Applying gates for pairs:
Even pair: (0, 1)
Odd pair: (1, 2)
Even pair: (2, 3)
Odd pair: (3, 4)
Even pair: (4, 5)
Step 3: Applying gates for pairs:
Even pair: (0, 1)
Odd pair: (1, 2)
Even pair: (2, 3)
Odd pair: (3, 4)
Even pair: (4, 5)
Step 4: Applying gates for pairs:
Even pair: (0, 1)
Odd pair: (1, 2)
Even pair: (2, 3)
Odd pair: (3, 4)
Even pair: (4, 5)
Step 5: Applying gates for pairs:
Even pair: (0, 1)
Odd pair: (1, 2)
Even pair: (2, 3)
Odd pair: (3, 4)
Even pair: (4, 5)
Step 6: Applying gates for pairs:
Even pair: (0, 1)
Odd pair: (1, 2)
Even pair: (2, 3)
Odd pair: (3, 4)
Even pair: (4, 5)
Step 7: Applying gates for pairs:
Even pair: (0, 1)
Odd pair: (1, 2)
Even pair: (2, 3)
Odd pair: (3, 4)
Even pair: (4, 5)
Step 8: Applying gates f

/var/folders/zr/_ww60qvd18j868qh1qhtky300000gn/T/ipykernel_95810/2407775287.py:8: DeprecationWarning: Treating CircuitInstruction as an iterable is deprecated legacy behavior since Qiskit 1.2, and will be removed in Qiskit 3.0. Instead, use the `operation`, `qubits` and `clbits` named attributes.
  for gate, qargs, _ in circuit.data:
/var/folders/zr/_ww60qvd18j868qh1qhtky300000gn/T/ipykernel_95810/2407775287.py:28: DeprecationWarning: Treating CircuitInstruction as an iterable is deprecated legacy behavior since Qiskit 1.2, and will be removed in Qiskit 3.0. Instead, use the `operation`, `qubits` and `clbits` named attributes.
  for gate, qargs, _ in circuit.data:
